export { default as AWSIcon } from "@/assets/skills/aws.svg?react";
export { default as DockerIcon } from "@/assets/skills/docker.svg?react";
export { default as GraphQLIcon } from "@/assets/skills/graphql.svg?react";
export { default as JavaScriptIcon } from "@/assets/skills/js.svg?react";
export { default as ReactIcon } from "@/assets/skills/react.svg?react";
export { default as ReduxIcon } from "@/assets/skills/redux.svg?react";
export { default as TypeScriptIcon } from "@/assets/skills/ts.svg?react";
export { default as VueIcon } from "@/assets/skills/vue.svg?react";
export { default as WebpackIcon } from "@/assets/skills/webpack.svg?react";
